#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1PITCH_VALUE(const char *paramName, const asn1SccPITCH_VALUE *pData);
void PrintASN1RESOLUTION(const char *paramName, const asn1SccRESOLUTION *pData);
void PrintASN1VALIDITY(const char *paramName, const asn1SccVALIDITY *pData);
void PrintASN1PITCH_SEQ(const char *paramName, const asn1SccPITCH_SEQ *pData);
void PrintASN1MyInteger(const char *paramName, const asn1SccMyInteger *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1T_Null_Record(const char *paramName, const asn1SccT_Null_Record *pData);

#ifdef __cplusplus
}
#endif

#endif
