
/* Header file for function EGSE in GUI language
 * Generated by TASTE on 2022-07-12 21:19:51
 * Context Parameters present : NO
 * Provided interfaces : GetPitchValue, Poll
 * Required interfaces : SetTargetPitch
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void egse_startup(void);

/* Provided interfaces */
void egse_PI_GetPitchValue( const asn1SccPITCH_SEQ * );


void egse_PI_Poll( void );

/* Required interfaces */
extern void egse_RI_SetTargetPitch( const asn1SccPITCH_VALUE * );


#ifdef __cplusplus
}
#endif

