/* Message identifiers for the GUI messages
 * Used by the code of the GUIs and by the ctypes Python interface
 * DO NOT EDIT THIS FILE MANUALLY - MODIFY THE KAZOO TEMPLATE IF NECESSARY
*/
#pragma once

// 2 getpitchvalue, poll
typedef enum {
   i_GetPitchValue
} T_egse_PI_list;

typedef enum {
   i_SetTargetPitch
} T_egse_RI_list;

