pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");



package CPPEXAMPLE_DATAVIEW with SPARK_Mode
is


subtype asn1SccMyInteger is adaasn1rtl.Asn1UInt range 0 .. 10000;


function asn1SccMyInteger_Equal(val1, val2 : asn1SccMyInteger) return Boolean;

function asn1SccMyInteger_Init return asn1SccMyInteger;

ERR_MYINTEGER:constant Integer := 1; 
function asn1SccMyInteger_IsConstraintValid(val : asn1SccMyInteger) return adaasn1rtl.ASN1_RESULT;
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide CPPEXAMPLE_DATAVIEW;


end CPPEXAMPLE_DATAVIEW;