-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by Kazoo (templates/glue/language_wrappers/ri_adb/function.tmplt)
-- Date : 2022-07-12 21:42:48
package body Ks_RI is

   procedure Getpitchvalue
      (Pitchdata : in out asn1SccPitch_Seq) is
      procedure C_Getpitchvalue
         (Pitchdata : in out asn1SccPitch_Seq)
         with Import,
              Convention => C,
              Link_Name  => "ks_RI_GetPitchValue";
   begin
         C_Getpitchvalue (pitchData);
   end Getpitchvalue;

end Ks_RI;
