
/* Header file for function KS in CPP language
 * Generated by TASTE on 2022-07-12 21:19:51
 * Context Parameters present : NO
 * Provided interfaces : PitchControlLoop, SetTargetPitch
 * Required interfaces : GetPitchValue
 * User-defined properties for this function:
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void ks_startup(void);

/* Provided interfaces */
void ks_PI_PitchControlLoop( );


void ks_PI_SetTargetPitch( const asn1SccPITCH_VALUE * );

/* Required interfaces */
extern void ks_RI_GetPitchValue( const asn1SccPITCH_SEQ * );


#ifdef __cplusplus
}
#endif

