pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");


pragma Warnings (Off, "no entities of ""PitchTM"" are referenced");
pragma Warnings (Off, "use clause for package ""PitchTM"" has no effect");
with PitchTM; use PitchTM;
pragma Warnings (On, "no entities of ""PitchTM"" are referenced");
pragma Warnings (On, "use clause for package ""PitchTM"" has no effect");



package Ks_Datamodel with SPARK_Mode
is


subtype asn1SccKs_States_index_range is Integer range 0..1;
type asn1SccKs_States is (asn1Scccontrol, asn1Sccidle) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccKs_States use
    (asn1Scccontrol => 0, asn1Sccidle => 1);

function asn1SccKs_States_Equal(val1, val2 : asn1SccKs_States) return Boolean;

function asn1SccKs_States_Init return asn1SccKs_States;

ERR_KS_STATES:constant Integer := 1; 
function asn1SccKs_States_IsConstraintValid(val : asn1SccKs_States) return adaasn1rtl.ASN1_RESULT;
-- asn1SccKs_Context --------------------------------------------

type asn1SccKs_Context is record 
    state : asn1SccKs_States;
    init_done : adaasn1rtl.Asn1Boolean;
    pitch : PitchTM.asn1SccPITCH_SEQ;
    targetpitch : PitchTM.asn1SccPITCH_VALUE;
end record;


function asn1SccKs_Context_Equal(val1, val2 : asn1SccKs_Context) return Boolean;

function asn1SccKs_Context_Init return asn1SccKs_Context;

ERR_KS_CONTEXT:constant Integer := 71; 
ERR_KS_CONTEXT_STATE_2:constant Integer := 11; 
ERR_KS_CONTEXT_INIT_DONE:constant Integer := 16; 
ERR_KS_CONTEXT_PITCH_2:constant Integer := 56; 
ERR_KS_CONTEXT_TARGETPITCH_2:constant Integer := 66; 
function asn1SccKs_Context_IsConstraintValid(val : asn1SccKs_Context) return adaasn1rtl.ASN1_RESULT;
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide Ks_Datamodel;


end Ks_Datamodel;